apiVersion: v1
kind: Secret
metadata:
  name: booking-api-secrets
  namespace: secure-booking
type: Opaque
stringData:
  SECRET_KEY: "prod-enterprise-hardened-jwt-signing-secret-key-2026-cys401"
  DB_PASSWORD: "database-internal-encryption-key-phrase"
